
import { Bag, OutfitVibe } from './types';

export const OUTFIT_VIBES: OutfitVibe[] = [
    { id: 'chic_parisian', name: 'Chic Parisian' },
    { id: 'elevated_athleisure', name: 'Elevated Athleisure' },
    { id: 'scandinavian_minimalist', name: 'Scandinavian Minimalist' },
    { id: 'tokyo_streetwear', name: 'Tokyo Streetwear' },
    { id: 'la_bohemian', name: 'LA Bohemian' },
    { id: 'corporate_core', name: 'Corporate Core' },
    { id: 'elegant_evening', name: 'Elegant Evening' },
    { id: 'party_club', name: 'Party/Club' },
    { id: 'date_night', name: 'Date Night' },
    { id: 'resort_wear', name: 'Resort Wear' },
];

export const BAG_CATALOG: Bag[] = [
  { id: 'sl-1', brand: 'Saint Laurent', model: 'Cassandre', color: 'black leather', material: 'Grain de Poudre embossed calfskin leather', styleCode: '377828BOW011000', details: 'Black grain de poudre matelassé leather with gold-tone YSL monogram hardware, removable chain strap, envelope flap with magnetic snap closure.', category: 'Crossbody' },
  { id: 'loewe-1', brand: 'Loewe', model: 'Puzzle', color: 'tan leather', material: 'Classic calfskin leather', styleCode: 'A510S21X50', details: 'Tan classic calfskin leather with a cuboid shape and distinctive geometric lines, top handle, removable shoulder strap, and embossed Anagram.', category: 'Shoulder Bag' },
  { id: 'gucci-1', brand: 'Gucci', model: 'Dionysus', color: 'black with gold hardware', material: 'Black GG Supreme canvas and suede', styleCode: '400249 KHNRN 8642', details: 'Black GG Supreme canvas with black suede detail, featuring a distinctive tiger head spur closure with gold-tone hardware and a sliding chain strap.', category: 'Shoulder Bag' },
  { id: 'bv-1', brand: 'Bottega Veneta', model: 'Jodie', color: 'ice cream white', material: 'Intrecciato Nappa leather', styleCode: '600261VCPP09009', details: 'Ice cream white intrecciato woven Nappa leather with a signature knotted top handle, soft slouchy shape, and zip closure.', category: 'Hobo Bag' },
  { id: 'prada-1', brand: 'Prada', model: 'Re-Edition 2005', color: 'nylon beige', material: 'Re-Nylon gabardine fabric', styleCode: '1BH204_064_F0F24_V_V1L', details: 'Beige Re-Nylon fabric shoulder bag with Saffiano leather trim, detachable pouch, and silver-tone hardware. An iconic Miuccia Prada design.', category: 'Shoulder Bag' },
  { id: 'celine-1', brand: 'Celine', model: 'Triomphe', color: 'classic tan', material: 'Natural calfskin leather', styleCode: '187363BF4.04LU', details: 'Classic tan natural calfskin leather with a vintage-inspired Triomphe metallic closure, adjustable leather shoulder strap, and structured silhouette.', category: 'Shoulder Bag' },
  { id: 'dior-1', brand: 'Dior', model: 'Saddle Bag', color: 'blue oblique jacquard', material: 'Dior Oblique jacquard canvas', styleCode: 'M0446CRIW_M928', details: 'Blue Dior Oblique jacquard canvas with the iconic saddle shape, magnetic D-stirrup closure, and antique gold-finish metal hardware.', category: 'Shoulder Bag' },
  { id: 'fendi-1', brand: 'Fendi', model: 'Baguette', color: 'brown jacquard FF', material: 'FF motif jacquard fabric', styleCode: '8BR600A6V5F17U4', details: 'Brown jacquard fabric with the iconic FF motif, FF clasp, and featuring a front flap and magnetic clasp. Can be carried by hand or worn cross-body.', category: 'Shoulder Bag' },
  { id: 'chanel-1', brand: 'Chanel', model: 'Classic Flap', color: 'black caviar leather', material: 'Grained calfskin (Caviar)', styleCode: 'A01112 Y01864 C3906', details: 'Black grained calfskin (caviar) leather with signature diamond quilting, interlocking CC clasp, and woven leather-chain strap. Timeless and iconic.', category: 'Shoulder Bag' },
  { id: 'hermes-1', brand: 'Hermès', model: 'Kelly 25', color: 'etoupe togo leather', material: 'Togo calfskin leather', styleCode: 'H044624CK18', details: 'Etoupe Togo calfskin leather with a trapezoidal shape, two triangular gussets, a cutout flap, a handle, and a signature turn-lock closure with palladium hardware.', category: 'Top Handle' },
  { id: 'balenciaga-1', brand: 'Balenciaga', model: 'City', color: 'black motorcycle leather', material: 'Arena lambskin leather', styleCode: '115748D94JN1000', details: 'Black soft Arena lambskin leather with motorcycle-inspired details, including studs, buckles, and a whipstitched top handle.', category: 'Top Handle' },
  { id: 'chloe-1', brand: 'Chloé', model: 'Marcie', color: 'cashmere grey', material: 'Grained calfskin leather', styleCode: 'CHC21AS660F01053', details: 'Cashmere grey grained calfskin with a distinctive horseshoe-shaped front flap, decorative saddle stitching, and tassel details.', category: 'Satchel' },
  { id: 'givenchy-1', brand: 'Givenchy', model: 'Antigona', color: 'black sugar leather', material: 'Grained goatskin (Sugar) leather', styleCode: 'BB05117012-001', details: 'Black grained "sugar" goatskin leather with a structured, Boston bag silhouette, oversized zip, and metal logo lettering.', category: 'Satchel' },
  { id: 'valentino-1', brand: 'Valentino', model: 'Rockstud Spike', color: 'nude nappa leather', material: 'Quilted Nappa lambskin leather', styleCode: 'VW2B0122NAP16Q', details: 'Nude quilted Nappa lambskin leather embellished with small platinum-finish pyramid studs, featuring a top handle and sliding chain strap.', category: 'Shoulder Bag' },
  { id: 'miumiu-1', brand: 'Miu Miu', model: 'Wander Matelassé', color: 'blush pink', material: 'Matelassé Nappa leather', styleCode: '5BH188_N88_F0615_V_OOO', details: 'Blush pink Matelassé Nappa leather with a hobo bag shape, distinctive quilting, and metal logo lettering on the front.', category: 'Hobo Bag' },
  { id: 'jacquemus-1', brand: 'Jacquemus', model: 'Le Chiquito', color: 'white leather', material: 'Smooth calfskin leather', styleCode: '203BA01-203 300100', details: 'A micro bag in white smooth calfskin leather with a reinforced top handle, magnetic flap closure, and gold-tone metal logo.', category: 'Micro Bag' },
  { id: 'therow-1', brand: 'The Row', model: 'Margaux 15', color: 'saddle brown leather', material: 'Saddle leather', styleCode: 'W1255L72CGSG', details: 'Saddle brown smooth calfskin leather with a refined, minimalist design, belted gusseted side panels, and interior toggle closure.', category: 'Satchel' },
  { id: 'paco-1', brand: 'Paco Rabanne', model: '1969', color: 'silver metal mesh', material: 'Brass metal mesh', styleCode: '20ASS0001MET089P040', details: 'Iconic silver metal mesh bag made of assembled brass paillettes, with a chain link shoulder strap. A re-edition of the 1969 original.', category: 'Shoulder Bag' },
  { id: 'coperni-1', brand: 'Coperni', model: 'Swipe Bag', color: 'black glass', material: 'Hand-blown glass', styleCode: 'COPF22BA01G-BLACK', details: 'A sculptural bag made entirely of hand-blown black glass, inspired by the iPhone\'s swipe-to-unlock icon. A piece of wearable art.', category: 'Clutch' },
  { id: 'apc-1', brand: 'A.P.C.', model: 'Demi-Lune', color: 'smooth black leather', material: 'Vegetable-tanned Spanish leather', styleCode: 'PXBJQ-F61048-LZZ', details: 'Smooth black vegetable-tanned Spanish leather in a half-moon shape, with a two-way zip closure and gold-tone \'A.P.C. rue Madame Paris\' logo.', category: 'Crossbody' },
  { id: 'byfar-1', brand: 'By Far', model: 'Rachel', color: 'cream patent leather', material: 'Patent calfskin leather', styleCode: '20SSRCLSCCECMED', details: 'Cream patent calfskin leather with a 90s-inspired baguette silhouette, short shoulder strap, and top zip closure.', category: 'Shoulder Bag' },
  { id: 'staud-1', brand: 'Staud', model: 'Moon Bag', color: 'cognac croc-embossed', material: 'Croc-embossed leather', styleCode: '27-9042-COG', details: 'Cognac croc-embossed leather in a unique crescent moon shape with a circular top handle and magnetic closure.', category: 'Top Handle' },
  { id: 'goyard-1', brand: 'Goyard', model: 'St Louis PM', color: 'classic black and tan', material: 'Goyardine canvas and leather', styleCode: 'STLOUIPMLTY01CL01P', details: 'Classic black and tan Goyardine canvas with black leather trim. A lightweight, reversible, and unstructured tote bag with a detachable pochette.', category: 'Tote' },
  { id: 'lv-1', brand: 'Louis Vuitton', model: 'Speedy 25', color: 'monogram canvas', material: 'Monogram coated canvas', styleCode: 'M41109', details: 'Iconic Monogram coated canvas with natural cowhide leather trim, a compact shape, rolled leather handles, and engraved padlock.', category: 'Top Handle' },
  { id: 'hermes-2', brand: 'Hermès', model: 'Birkin 30', color: 'gold togo leather', material: 'Togo calfskin leather', styleCode: 'H047523CK37', details: 'Gold (a rich tan) Togo calfskin leather with a spacious interior, rolled top handles, a flap top closure with a turn-lock, and palladium hardware.', category: 'Top Handle' },
];
